from typing import List, Optional

class CifEntry:
    id: str
    type: str
    values: List[str]

    def __init__(self) -> None: ...

class CifDictionary:
    def __init__(self) -> None: ...
    def parse(self, filename: str) -> bool: ...
    def get_entry(self, id: str) -> Optional[CifEntry]: ...
    def get_categories(self) -> List[str]: ...