from typing import Iterator

class FastaEntry:
    header: str
    sequence: str

    def __init__(self) -> None: ...

class FastaIterator:
    def __init__(self, filename: str) -> None: ...
    def next(self, entry: FastaEntry) -> bool: ...
    def reset(self) -> None: ...
    def is_valid(self) -> bool: ...
    def __iter__(self) -> Iterator[FastaEntry]: ...