from typing import List

class MSAConverter:
    def __init__(self) -> None: ...
    def fasta_to_matrix(self, filename: str) -> List[List[str]]: ...
    def matrix_to_fasta(self, matrix: List[List[str]], headers: List[str], output_file: str) -> bool: ...
    @staticmethod
    def validate_alignment(matrix: List[List[str]]) -> bool: ...
    @staticmethod
    def get_alignment_length(matrix: List[List[str]]) -> int: ...
    @staticmethod
    def get_sequence_count(matrix: List[List[str]]) -> int: ...